In [1]:
import numpy as np

In [2]:
cap = 5
doc = 50
hosp = 10

In [3]:
import random

In [4]:
mat2 = np.empty([doc,hosp])
for i in range(doc):
    mat2[i,:]=np.array(random.sample(range(hosp),hosp))    

In [5]:
mat2 = mat2 + np.ones((doc,hosp))

In [6]:
## adding the rows and columns for supply and demand

In [7]:
capacities = np.full((1,hosp), cap) #demand

In [8]:
capacities

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [9]:
capacities.shape

(1, 10)

In [10]:
mat2.shape

(50, 10)

In [11]:
mat2= np.append(mat2, capacities, axis=0)
mat2.shape

(51, 10)

### Least Cost Cell Method

Step 1: Find the cell with lowest cost. We have many (every doctor chose a hospital in 1st place). In the algorithm, we are supposed to choose the one with the lowest demand supply difference (ie everyone gets assigned). However, here, all of our hospitals are at the same capacity.

In [14]:
mat = mat2.copy()
mat

array([[ 8.,  1.,  2.,  9., 10.,  4.,  7.,  6.,  3.,  5.],
       [10.,  7.,  8.,  6.,  1.,  4.,  9.,  2.,  3.,  5.],
       [ 1.,  3.,  9.,  2.,  7.,  8.,  6., 10.,  4.,  5.],
       [ 3.,  2.,  1., 10.,  5.,  9.,  7.,  4.,  8.,  6.],
       [10.,  6.,  9.,  5.,  7.,  3.,  1.,  4.,  8.,  2.],
       [ 1.,  5.,  7.,  6.,  3.,  2.,  8.,  4.,  9., 10.],
       [ 8.,  1.,  4.,  5.,  3., 10.,  9.,  2.,  6.,  7.],
       [ 9., 10.,  6.,  3.,  8.,  1.,  5.,  7.,  2.,  4.],
       [ 3.,  6.,  9.,  2.,  5.,  8.,  4.,  7.,  1., 10.],
       [ 3.,  7.,  1.,  9.,  8., 10.,  2.,  5.,  4.,  6.],
       [10.,  5.,  8.,  1.,  7.,  9.,  2.,  4.,  6.,  3.],
       [10.,  8.,  2.,  1.,  9.,  6.,  4.,  7.,  3.,  5.],
       [ 7.,  2.,  5.,  8.,  6., 10.,  9.,  3.,  1.,  4.],
       [10.,  6.,  3.,  7.,  8.,  5.,  4.,  9.,  1.,  2.],
       [ 7.,  6.,  1.,  2., 10.,  5.,  9.,  3.,  8.,  4.],
       [ 2.,  3., 10.,  6.,  1.,  5.,  9.,  7.,  4.,  8.],
       [ 2.,  3., 10.,  9.,  6.,  7.,  5.,  8.,  4.,  1.

In [15]:
mat3 = np.sum(mat2[:-1,:],0)
hos = np.argmax(mat3)
num=0
mat3

array([294., 269., 267., 239., 293., 287., 300., 284., 248., 269.])

In [16]:
while (num <50):
    if(mat2[-1,hos] == 0 ):
        mat2[:-1,hos] = np.where(mat2[:-1,hos] < 11, -11, mat2[:-1,hos])
        mat3 = np.sum(mat2[:-1,:],0)
        hos = np.argmax(mat3)
    else:
        mat3 = np.sum(mat2[:-1,:],0)
        hos = np.argmax(mat3)
        mat2[-1,hos]-=1
        doc = np.argmin(mat2[:-1,hos])
        mat2[doc,]=11.01
        mat2[doc,hos]=11
        num +=1

In [17]:

num

50

In [136]:
mat3 = np.sum(mat2[:-1,:],0)
hos = np.argmax(mat3)
mat2[-1,hos]-=1
doc = np.argmin(mat2[:-1,hos])
mat2[doc,]=11.01
mat2[doc,hos]=11
num +=1

In [138]:
#if(mat2[-1,hos] == 0 ):
mat2[:-1,hos] = np.where(mat2[:-1,hos] < 11, -11, mat2[:-1,hos])

In [104]:
mat2 = test.copy()

In [19]:
mat

array([[ 8.,  1.,  2.,  9., 10.,  4.,  7.,  6.,  3.,  5.],
       [10.,  7.,  8.,  6.,  1.,  4.,  9.,  2.,  3.,  5.],
       [ 1.,  3.,  9.,  2.,  7.,  8.,  6., 10.,  4.,  5.],
       [ 3.,  2.,  1., 10.,  5.,  9.,  7.,  4.,  8.,  6.],
       [10.,  6.,  9.,  5.,  7.,  3.,  1.,  4.,  8.,  2.],
       [ 1.,  5.,  7.,  6.,  3.,  2.,  8.,  4.,  9., 10.],
       [ 8.,  1.,  4.,  5.,  3., 10.,  9.,  2.,  6.,  7.],
       [ 9., 10.,  6.,  3.,  8.,  1.,  5.,  7.,  2.,  4.],
       [ 3.,  6.,  9.,  2.,  5.,  8.,  4.,  7.,  1., 10.],
       [ 3.,  7.,  1.,  9.,  8., 10.,  2.,  5.,  4.,  6.],
       [10.,  5.,  8.,  1.,  7.,  9.,  2.,  4.,  6.,  3.],
       [10.,  8.,  2.,  1.,  9.,  6.,  4.,  7.,  3.,  5.],
       [ 7.,  2.,  5.,  8.,  6., 10.,  9.,  3.,  1.,  4.],
       [10.,  6.,  3.,  7.,  8.,  5.,  4.,  9.,  1.,  2.],
       [ 7.,  6.,  1.,  2., 10.,  5.,  9.,  3.,  8.,  4.],
       [ 2.,  3., 10.,  6.,  1.,  5.,  9.,  7.,  4.,  8.],
       [ 2.,  3., 10.,  9.,  6.,  7.,  5.,  8.,  4.,  1.

In [21]:
mat2 = np.where(mat2[:-1,:] > 11, 0, 1)

In [20]:
mattt = mat2.copy()

In [24]:
te = mat2*mat[:-1,:]

In [25]:
te

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 